/// <reference path="../pb_data/types.d.ts" />
// Increase maxSize of blog_articles content fields from 5000 to 50000 characters
// to support rich HTML content generated by TipTap / AI.
migrate((app) => {
  const col = app.findCollectionByNameOrId("blog_articles");

  for (const fieldName of ["content_pt", "content_en", "content_es"]) {
    const field = col.fields.getByName(fieldName);
    if (field) {
      field.max = 50000;
    }
  }

  app.save(col);
}, (app) => {
  const col = app.findCollectionByNameOrId("blog_articles");

  for (const fieldName of ["content_pt", "content_en", "content_es"]) {
    const field = col.fields.getByName(fieldName);
    if (field) {
      field.max = 5000;
    }
  }

  app.save(col);
});
